name: web_scraper
description: A simple web scraper to scrape HTML tags and their attributes to cast them into Lists and Maps for dart and flutter.
version: 0.1.4
homepage: https://github.com/tusharojha/web_scraper

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  html: ^0.15.4
  http: ^1.1.2

dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
